const express = require('express')
const router = express.Router()
var productsController = require('../src/products/productsController')

router.route('/api/session').get(productsController.sessionControllerFn)
router.route('/api/logout').get(productsController.logoutControllerFn)
router.route('/api/admins').get(productsController.fetchAdminsControllerFn)
router.route('/api/products').get(productsController.fetchProductsControllerFn)
router.route('/api/orders').get(productsController.fetchOrdersControllerFn)
router.route('/api/phonepetxn').get(productsController.fetchPhonepetxnControllerFn)
router.route('/api/googlepaytxn').get(productsController.fetchGooglepaytxnControllerFn)
router.route('/api/paypaltxn').get(productsController.fetchPaypaltxnControllerFn)
router.route('/api/razorpaytxn').get(productsController.fetchRazorpaytxnControllerFn)
router.route('/api/send-otp').post(productsController.sendOtpControllerFn)
router.route('/api/verify-otp').post(productsController.verifyOtpControllerFn)
router.route('/api/phonepe').post(productsController.phonepeControllerFn)
router.route('/api/googlepay').post(productsController.googlepayControllerFn)
router.route('/api/paypal-pay').post(productsController.paypalControllerFn)
router.route('/api/razorpay-pay').post(productsController.razorpayControllerFn)
router.route('/api/payments').post(productsController.paymentsControllerFn)
router.route('/api/products/create').post(productsController.createProductsControllerFn)
router.route('/api/orders/create').post(productsController.createOrdersControllerFn)
router.route('/api/phonepe/status').post(productsController.phonepestatusControllerFn)
router.route('/api/user-request/delete/:orderid').delete(productsController.deleteUserRequestControllerFn)


module.exports = router